from __future__ import annotations
import cocotb.handle
import cocotb.types
from typing import overload, Literal

# This file was automatically generated by copra
# It provides type stubs for your HDL design for use with cocotb

class AsconAead(cocotb.handle.HierarchyObject):
    ascon_core_inst: AsconCoreInst
    assoc_data_i: cocotb.handle.LogicArrayObject
    associated_data_word_left_i: cocotb.handle.LogicObject
    clk_i: cocotb.handle.LogicObject
    core_finished: cocotb.handle.LogicObject
    core_in: cocotb.handle.LogicArrayObject
    core_out: cocotb.handle.LogicArrayObject
    core_rounds: cocotb.handle.LogicArrayObject
    curr_state: cocotb.handle.LogicArrayObject
    encrypt_mode_i: cocotb.handle.LogicObject
    finished_o: cocotb.handle.LogicObject
    key: cocotb.handle.LogicArrayObject
    key_i: cocotb.handle.LogicArrayObject
    mask_high: cocotb.handle.LogicArrayObject
    mask_low: cocotb.handle.LogicArrayObject
    nonce_i: cocotb.handle.LogicArrayObject
    pad_high: cocotb.handle.LogicArrayObject
    pad_low: cocotb.handle.LogicArrayObject
    plaintext_word_left_i: cocotb.handle.LogicObject
    reset_i: cocotb.handle.LogicObject
    start_core: cocotb.handle.LogicObject
    start_i: cocotb.handle.LogicObject
    start_prev: cocotb.handle.LogicObject
    tag_o: cocotb.handle.LogicArrayObject
    text_i: cocotb.handle.LogicArrayObject
    text_len_i: cocotb.handle.LogicArrayObject
    text_o: cocotb.handle.LogicArrayObject
    text_ready_o: cocotb.handle.LogicObject
    word_processed_o: cocotb.handle.LogicObject

    @overload
    def __getitem__(self, name: Literal['clk_i']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['reset_i']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['start_i']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['associated_data_word_left_i']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['plaintext_word_left_i']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['encrypt_mode_i']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['finished_o']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['text_ready_o']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['word_processed_o']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['key_i']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['nonce_i']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['assoc_data_i']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['text_i']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['text_o']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['tag_o']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['text_len_i']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['start_core']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['core_finished']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['key']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['core_in']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['core_out']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['core_rounds']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['curr_state']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['mask_low']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['mask_high']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['pad_low']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['pad_high']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['start_prev']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['ascon_core_inst']) -> AsconCoreInst: ...

    @overload
    def __getitem__(self, name: str) -> cocotb.handle.SimHandleBase: ...


class AsconCoreInst(cocotb.handle.HierarchyObject):
    ascon_linear_layer_inst: AsconLinearLayerInst
    ascon_sbox_inst: AsconSboxInst
    clk_i: cocotb.handle.LogicObject
    constant_addition: cocotb.handle.LogicArrayObject
    curr_state: cocotb.handle.LogicArrayObject
    finished_o: cocotb.handle.LogicObject
    internal_state: cocotb.handle.LogicArrayObject
    linear_diffusion: cocotb.handle.LogicArrayObject
    nonlinear_substition: cocotb.handle.LogicArrayObject
    reset_i: cocotb.handle.LogicObject
    round_counter: cocotb.handle.LogicArrayObject
    rounds_i: cocotb.handle.LogicArrayObject
    rounds_to_perform: cocotb.handle.LogicArrayObject
    start_i: cocotb.handle.LogicObject
    state_i: cocotb.handle.LogicArrayObject
    state_o: cocotb.handle.LogicArrayObject

    @overload
    def __getitem__(self, name: Literal['clk_i']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['reset_i']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['start_i']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['finished_o']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['state_i']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['rounds_i']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['state_o']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['curr_state']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['internal_state']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['round_counter']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['rounds_to_perform']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['constant_addition']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['nonlinear_substition']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['linear_diffusion']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['ascon_sbox_inst']) -> AsconSboxInst: ...

    @overload
    def __getitem__(self, name: Literal['ascon_linear_layer_inst']) -> AsconLinearLayerInst: ...

    @overload
    def __getitem__(self, name: str) -> cocotb.handle.SimHandleBase: ...


class AsconLinearLayerInst(cocotb.handle.HierarchyObject):
    gen_slice(0): GenSlice(0)
    gen_slice(1): GenSlice(1)
    gen_slice(2): GenSlice(2)
    gen_slice(3): GenSlice(3)
    gen_slice(4): GenSlice(4)
    state_i: cocotb.handle.LogicArrayObject
    state_o: cocotb.handle.LogicArrayObject

    @overload
    def __getitem__(self, name: Literal['state_i']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['state_o']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['gen_slice(0)']) -> GenSlice(0): ...

    @overload
    def __getitem__(self, name: Literal['gen_slice(1)']) -> GenSlice(1): ...

    @overload
    def __getitem__(self, name: Literal['gen_slice(2)']) -> GenSlice(2): ...

    @overload
    def __getitem__(self, name: Literal['gen_slice(3)']) -> GenSlice(3): ...

    @overload
    def __getitem__(self, name: Literal['gen_slice(4)']) -> GenSlice(4): ...

    @overload
    def __getitem__(self, name: str) -> cocotb.handle.SimHandleBase: ...


class AsconSboxInst(cocotb.handle.HierarchyObject):
    gen_slice(0): GenSlice(0)
    gen_slice(1): GenSlice(1)
    gen_slice(2): GenSlice(2)
    gen_slice(3): GenSlice(3)
    gen_slice(4): GenSlice(4)
    state_i: cocotb.handle.LogicArrayObject
    state_o: cocotb.handle.LogicArrayObject

    @overload
    def __getitem__(self, name: Literal['state_i']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['state_o']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['gen_slice(0)']) -> GenSlice(0): ...

    @overload
    def __getitem__(self, name: Literal['gen_slice(1)']) -> GenSlice(1): ...

    @overload
    def __getitem__(self, name: Literal['gen_slice(2)']) -> GenSlice(2): ...

    @overload
    def __getitem__(self, name: Literal['gen_slice(3)']) -> GenSlice(3): ...

    @overload
    def __getitem__(self, name: Literal['gen_slice(4)']) -> GenSlice(4): ...

    @overload
    def __getitem__(self, name: str) -> cocotb.handle.SimHandleBase: ...

