from __future__ import annotations
import cocotb.handle
import cocotb.types
from typing import overload, Literal

# This file was automatically generated by copra
# It provides type stubs for your HDL design for use with cocotb

class AsconSbox(cocotb.handle.HierarchyObject):
    clk: cocotb.handle.LogicObject
    state_i: cocotb.handle.LogicArrayObject
    state_o: cocotb.handle.LogicArrayObject

    @overload
    def __getitem__(self, name: Literal['state_i']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['clk']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['state_o']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: str) -> cocotb.handle.SimHandleBase: ...

