from __future__ import annotations
import cocotb.handle
import cocotb.types
from typing import overload, Literal

# This file was automatically generated by copra
# It provides type stubs for your HDL design for use with cocotb

class AsconAed(cocotb.handle.HierarchyObject):
    a_i: cocotb.handle.LogicArrayObject
    ascon_core_inst: AsconCoreInst
    associated_data_word_left_i: cocotb.handle.LogicObject
    c_o: cocotb.handle.LogicArrayObject
    c_ready_o: cocotb.handle.LogicObject
    clk_i: cocotb.handle.LogicObject
    core_finished: cocotb.handle.LogicObject
    core_in: cocotb.handle.LogicArrayObject
    core_out: cocotb.handle.LogicArrayObject
    core_rounds: cocotb.handle.LogicArrayObject
    curr_state: cocotb.handle.LogicArrayObject
    debug_clock: cocotb.handle.LogicArrayObject
    error_o: cocotb.handle.LogicObject
    finished_o: cocotb.handle.LogicObject
    k_i: cocotb.handle.LogicArrayObject
    key: cocotb.handle.LogicArrayObject
    n_i: cocotb.handle.LogicArrayObject
    p_i: cocotb.handle.LogicArrayObject
    p_intermed_debug: cocotb.handle.LogicArrayObject
    p_len_i: cocotb.handle.LogicArrayObject
    plaintext_word_left_i: cocotb.handle.LogicObject
    reset_i: cocotb.handle.LogicObject
    start_core: cocotb.handle.LogicObject
    start_i: cocotb.handle.LogicObject
    t_o: cocotb.handle.LogicArrayObject
    word_processed_o: cocotb.handle.LogicObject

    @overload
    def __getitem__(self, name: Literal['clk_i']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['reset_i']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['start_i']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['associated_data_word_left_i']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['plaintext_word_left_i']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['finished_o']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['error_o']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['c_ready_o']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['word_processed_o']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['k_i']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['n_i']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['a_i']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['p_i']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['c_o']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['t_o']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['p_len_i']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['start_core']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['core_finished']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['key']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['core_in']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['core_out']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['core_rounds']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['curr_state']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['p_intermed_debug']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['debug_clock']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['ascon_core_inst']) -> AsconCoreInst: ...

    @overload
    def __getitem__(self, name: str) -> cocotb.handle.SimHandleBase: ...


class AsconCoreInst(cocotb.handle.HierarchyObject):
    ascon_linear_layer_inst: AsconLinearLayerInst
    ascon_sbox_inst: AsconSboxInst
    clk_i: cocotb.handle.LogicObject
    constant_addition: cocotb.handle.LogicArrayObject
    curr_state: cocotb.handle.LogicArrayObject
    finished_o: cocotb.handle.LogicObject
    internal_state: cocotb.handle.LogicArrayObject
    linear_diffusion: cocotb.handle.LogicArrayObject
    nonlinear_substition: cocotb.handle.LogicArrayObject
    reset_i: cocotb.handle.LogicObject
    round_counter: cocotb.handle.LogicArrayObject
    rounds_i: cocotb.handle.LogicArrayObject
    rounds_to_perform: cocotb.handle.LogicArrayObject
    start_i: cocotb.handle.LogicObject
    state_i: cocotb.handle.LogicArrayObject
    state_o: cocotb.handle.LogicArrayObject

    @overload
    def __getitem__(self, name: Literal['clk_i']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['reset_i']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['start_i']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['finished_o']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['state_i']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['rounds_i']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['state_o']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['curr_state']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['internal_state']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['round_counter']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['rounds_to_perform']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['constant_addition']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['nonlinear_substition']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['linear_diffusion']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['ascon_sbox_inst']) -> AsconSboxInst: ...

    @overload
    def __getitem__(self, name: Literal['ascon_linear_layer_inst']) -> AsconLinearLayerInst: ...

    @overload
    def __getitem__(self, name: str) -> cocotb.handle.SimHandleBase: ...


class AsconLinearLayerInst(cocotb.handle.HierarchyObject):
    state_i: cocotb.handle.LogicArrayObject
    state_o: cocotb.handle.LogicArrayObject

    @overload
    def __getitem__(self, name: Literal['state_i']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['state_o']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: str) -> cocotb.handle.SimHandleBase: ...


class AsconSboxInst(cocotb.handle.HierarchyObject):
    state_i: cocotb.handle.LogicArrayObject
    state_o: cocotb.handle.LogicArrayObject

    @overload
    def __getitem__(self, name: Literal['state_i']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['state_o']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: str) -> cocotb.handle.SimHandleBase: ...

