from __future__ import annotations
import cocotb.handle
import cocotb.types
from typing import overload, Literal

# This file was automatically generated by copra
# It provides type stubs for your HDL design for use with cocotb

class AsconHash256(cocotb.handle.HierarchyObject):
    ascon_core_inst: AsconCoreInst
    clk_i: cocotb.handle.LogicObject
    core_finished: cocotb.handle.LogicObject
    core_in: cocotb.handle.LogicArrayObject
    core_out: cocotb.handle.LogicArrayObject
    curr_state: cocotb.handle.LogicArrayObject
    finished_o: cocotb.handle.LogicObject
    h_0: cocotb.handle.LogicArrayObject
    h_1: cocotb.handle.LogicArrayObject
    h_2: cocotb.handle.LogicArrayObject
    message_digest_o: cocotb.handle.LogicArrayObject
    message_i: cocotb.handle.LogicArrayObject
    reset_i: cocotb.handle.LogicObject
    squeeze_counter: cocotb.handle.LogicArrayObject
    start_core: cocotb.handle.LogicObject
    start_i: cocotb.handle.LogicObject
    word_left_i: cocotb.handle.LogicObject
    word_processed_o: cocotb.handle.LogicObject

    @overload
    def __getitem__(self, name: Literal['clk_i']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['reset_i']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['start_i']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['word_left_i']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['finished_o']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['word_processed_o']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['message_digest_o']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['message_i']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['curr_state']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['start_core']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['core_finished']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['core_in']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['core_out']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['squeeze_counter']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['h_0']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['h_1']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['h_2']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['ascon_core_inst']) -> AsconCoreInst: ...

    @overload
    def __getitem__(self, name: str) -> cocotb.handle.SimHandleBase: ...


class AsconCoreInst(cocotb.handle.HierarchyObject):
    ascon_linear_layer_inst: AsconLinearLayerInst
    ascon_sbox_inst: AsconSboxInst
    clk_i: cocotb.handle.LogicObject
    constant_addition: cocotb.handle.LogicArrayObject
    curr_state: cocotb.handle.LogicArrayObject
    finished_o: cocotb.handle.LogicObject
    internal_state: cocotb.handle.LogicArrayObject
    linear_diffusion: cocotb.handle.LogicArrayObject
    nonlinear_substition: cocotb.handle.LogicArrayObject
    reset_i: cocotb.handle.LogicObject
    round_counter: cocotb.handle.LogicArrayObject
    rounds_i: cocotb.handle.LogicArrayObject
    rounds_to_perform: cocotb.handle.LogicArrayObject
    start_i: cocotb.handle.LogicObject
    state_i: cocotb.handle.LogicArrayObject
    state_o: cocotb.handle.LogicArrayObject

    @overload
    def __getitem__(self, name: Literal['clk_i']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['reset_i']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['start_i']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['finished_o']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['state_i']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['rounds_i']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['state_o']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['curr_state']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['internal_state']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['round_counter']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['rounds_to_perform']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['constant_addition']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['nonlinear_substition']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['linear_diffusion']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['ascon_sbox_inst']) -> AsconSboxInst: ...

    @overload
    def __getitem__(self, name: Literal['ascon_linear_layer_inst']) -> AsconLinearLayerInst: ...

    @overload
    def __getitem__(self, name: str) -> cocotb.handle.SimHandleBase: ...


class AsconLinearLayerInst(cocotb.handle.HierarchyObject):
    state_i: cocotb.handle.LogicArrayObject
    state_o: cocotb.handle.LogicArrayObject

    @overload
    def __getitem__(self, name: Literal['state_i']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['state_o']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: str) -> cocotb.handle.SimHandleBase: ...


class AsconSboxInst(cocotb.handle.HierarchyObject):
    state_i: cocotb.handle.LogicArrayObject
    state_o: cocotb.handle.LogicArrayObject

    @overload
    def __getitem__(self, name: Literal['state_i']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['state_o']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: str) -> cocotb.handle.SimHandleBase: ...

