from __future__ import annotations
import cocotb.handle
import cocotb.types
from typing import overload, Literal

# This file was automatically generated by copra
# It provides type stubs for your HDL design for use with cocotb

class Asconaead128(cocotb.handle.HierarchyObject):
    asconaead128_slave_lite_v1_0_s00_axi_inst: Asconaead128SlaveLiteV10S00AxiInst
    debug_clock: cocotb.handle.LogicArrayObject
    s00_axi_aclk: cocotb.handle.LogicObject
    s00_axi_araddr: cocotb.handle.LogicArrayObject
    s00_axi_aresetn: cocotb.handle.LogicObject
    s00_axi_arprot: cocotb.handle.LogicArrayObject
    s00_axi_arready: cocotb.handle.LogicObject
    s00_axi_arvalid: cocotb.handle.LogicObject
    s00_axi_awaddr: cocotb.handle.LogicArrayObject
    s00_axi_awprot: cocotb.handle.LogicArrayObject
    s00_axi_awready: cocotb.handle.LogicObject
    s00_axi_awvalid: cocotb.handle.LogicObject
    s00_axi_bready: cocotb.handle.LogicObject
    s00_axi_bresp: cocotb.handle.LogicArrayObject
    s00_axi_bvalid: cocotb.handle.LogicObject
    s00_axi_rdata: cocotb.handle.LogicArrayObject
    s00_axi_rready: cocotb.handle.LogicObject
    s00_axi_rresp: cocotb.handle.LogicArrayObject
    s00_axi_rvalid: cocotb.handle.LogicObject
    s00_axi_wdata: cocotb.handle.LogicArrayObject
    s00_axi_wready: cocotb.handle.LogicObject
    s00_axi_wstrb: cocotb.handle.LogicArrayObject
    s00_axi_wvalid: cocotb.handle.LogicObject

    @overload
    def __getitem__(self, name: Literal['s00_axi_aclk']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['s00_axi_aresetn']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['s00_axi_awaddr']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['s00_axi_awprot']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['s00_axi_awvalid']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['s00_axi_awready']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['s00_axi_wdata']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['s00_axi_wstrb']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['s00_axi_wvalid']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['s00_axi_wready']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['s00_axi_bresp']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['s00_axi_bvalid']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['s00_axi_bready']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['s00_axi_araddr']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['s00_axi_arprot']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['s00_axi_arvalid']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['s00_axi_arready']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['s00_axi_rdata']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['s00_axi_rresp']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['s00_axi_rvalid']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['s00_axi_rready']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['debug_clock']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['asconaead128_slave_lite_v1_0_s00_axi_inst']) -> Asconaead128SlaveLiteV10S00AxiInst: ...

    @overload
    def __getitem__(self, name: str) -> cocotb.handle.SimHandleBase: ...


class Asconaead128SlaveLiteV10S00AxiInst(cocotb.handle.HierarchyObject):
    active_high_reset: cocotb.handle.LogicObject
    ascon_aead_inst: AsconAeadInst
    assoc_data_i: cocotb.handle.LogicArrayObject
    axi_araddr: cocotb.handle.LogicArrayObject
    axi_arready: cocotb.handle.LogicObject
    axi_awaddr: cocotb.handle.LogicArrayObject
    axi_awready: cocotb.handle.LogicObject
    axi_bresp: cocotb.handle.LogicArrayObject
    axi_bvalid: cocotb.handle.LogicObject
    axi_rresp: cocotb.handle.LogicArrayObject
    axi_rvalid: cocotb.handle.LogicObject
    axi_wready: cocotb.handle.LogicObject
    byte_index: cocotb.handle.LogicArrayObject
    clear_text_latch_prev: cocotb.handle.LogicObject
    finished_o: cocotb.handle.LogicObject
    key_i: cocotb.handle.LogicArrayObject
    latched_finished: cocotb.handle.LogicObject
    latched_tag_o: cocotb.handle.LogicArrayObject
    latched_text_o: cocotb.handle.LogicArrayObject
    latched_text_ready: cocotb.handle.LogicObject
    latched_word_processed: cocotb.handle.LogicObject
    mem_logic: cocotb.handle.LogicArrayObject
    nonce_i: cocotb.handle.LogicArrayObject
    s_axi_aclk: cocotb.handle.LogicObject
    s_axi_araddr: cocotb.handle.LogicArrayObject
    s_axi_aresetn: cocotb.handle.LogicObject
    s_axi_arprot: cocotb.handle.LogicArrayObject
    s_axi_arready: cocotb.handle.LogicObject
    s_axi_arvalid: cocotb.handle.LogicObject
    s_axi_awaddr: cocotb.handle.LogicArrayObject
    s_axi_awprot: cocotb.handle.LogicArrayObject
    s_axi_awready: cocotb.handle.LogicObject
    s_axi_awvalid: cocotb.handle.LogicObject
    s_axi_bready: cocotb.handle.LogicObject
    s_axi_bresp: cocotb.handle.LogicArrayObject
    s_axi_bvalid: cocotb.handle.LogicObject
    s_axi_rdata: cocotb.handle.LogicArrayObject
    s_axi_rready: cocotb.handle.LogicObject
    s_axi_rresp: cocotb.handle.LogicArrayObject
    s_axi_rvalid: cocotb.handle.LogicObject
    s_axi_wdata: cocotb.handle.LogicArrayObject
    s_axi_wready: cocotb.handle.LogicObject
    s_axi_wstrb: cocotb.handle.LogicArrayObject
    s_axi_wvalid: cocotb.handle.LogicObject
    slv_reg0: cocotb.handle.LogicArrayObject
    slv_reg1: cocotb.handle.LogicArrayObject
    slv_reg10: cocotb.handle.LogicArrayObject
    slv_reg11: cocotb.handle.LogicArrayObject
    slv_reg12: cocotb.handle.LogicArrayObject
    slv_reg13: cocotb.handle.LogicArrayObject
    slv_reg14: cocotb.handle.LogicArrayObject
    slv_reg15: cocotb.handle.LogicArrayObject
    slv_reg16: cocotb.handle.LogicArrayObject
    slv_reg17: cocotb.handle.LogicArrayObject
    slv_reg18: cocotb.handle.LogicArrayObject
    slv_reg19: cocotb.handle.LogicArrayObject
    slv_reg2: cocotb.handle.LogicArrayObject
    slv_reg20: cocotb.handle.LogicArrayObject
    slv_reg21: cocotb.handle.LogicArrayObject
    slv_reg22: cocotb.handle.LogicArrayObject
    slv_reg23: cocotb.handle.LogicArrayObject
    slv_reg24: cocotb.handle.LogicArrayObject
    slv_reg25: cocotb.handle.LogicArrayObject
    slv_reg26: cocotb.handle.LogicArrayObject
    slv_reg3: cocotb.handle.LogicArrayObject
    slv_reg4: cocotb.handle.LogicArrayObject
    slv_reg5: cocotb.handle.LogicArrayObject
    slv_reg6: cocotb.handle.LogicArrayObject
    slv_reg7: cocotb.handle.LogicArrayObject
    slv_reg8: cocotb.handle.LogicArrayObject
    slv_reg9: cocotb.handle.LogicArrayObject
    start_core_o: cocotb.handle.LogicObject
    state_read: cocotb.handle.LogicArrayObject
    state_write: cocotb.handle.LogicArrayObject
    status_register: cocotb.handle.LogicArrayObject
    tag_o: cocotb.handle.LogicArrayObject
    text_i: cocotb.handle.LogicArrayObject
    text_len_i: cocotb.handle.LogicArrayObject
    text_o: cocotb.handle.LogicArrayObject
    text_ready_o: cocotb.handle.LogicObject
    word_processed_o: cocotb.handle.LogicObject

    @overload
    def __getitem__(self, name: Literal['s_axi_aclk']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['s_axi_aresetn']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['s_axi_awaddr']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['s_axi_awprot']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['s_axi_awvalid']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['s_axi_awready']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['s_axi_wdata']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['s_axi_wstrb']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['s_axi_wvalid']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['s_axi_wready']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['s_axi_bresp']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['s_axi_bvalid']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['s_axi_bready']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['s_axi_araddr']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['s_axi_arprot']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['s_axi_arvalid']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['s_axi_arready']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['s_axi_rdata']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['s_axi_rresp']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['s_axi_rvalid']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['s_axi_rready']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['axi_awaddr']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['axi_awready']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['axi_wready']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['axi_bresp']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['axi_bvalid']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['axi_araddr']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['axi_arready']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['axi_rresp']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['axi_rvalid']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['slv_reg0']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['slv_reg1']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['slv_reg2']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['slv_reg3']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['slv_reg4']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['slv_reg5']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['slv_reg6']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['slv_reg7']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['slv_reg8']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['slv_reg9']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['slv_reg10']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['slv_reg11']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['slv_reg12']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['slv_reg13']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['slv_reg14']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['slv_reg15']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['slv_reg16']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['slv_reg17']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['slv_reg18']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['slv_reg19']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['slv_reg20']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['slv_reg21']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['slv_reg22']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['slv_reg23']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['slv_reg24']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['slv_reg25']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['slv_reg26']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['byte_index']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['mem_logic']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['state_read']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['state_write']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['active_high_reset']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['status_register']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['clear_text_latch_prev']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['latched_text_o']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['latched_tag_o']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['latched_finished']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['latched_text_ready']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['latched_word_processed']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['key_i']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['nonce_i']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['assoc_data_i']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['text_i']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['text_len_i']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['start_core_o']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['finished_o']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['text_ready_o']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['word_processed_o']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['text_o']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['tag_o']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['ascon_aead_inst']) -> AsconAeadInst: ...

    @overload
    def __getitem__(self, name: str) -> cocotb.handle.SimHandleBase: ...


class AsconAeadInst(cocotb.handle.HierarchyObject):
    ascon_core_inst: AsconCoreInst
    assoc_data_i: cocotb.handle.LogicArrayObject
    associated_data_word_left_i: cocotb.handle.LogicObject
    clk_i: cocotb.handle.LogicObject
    core_finished: cocotb.handle.LogicObject
    core_finished_latched: cocotb.handle.LogicObject
    core_in: cocotb.handle.LogicArrayObject
    core_out: cocotb.handle.LogicArrayObject
    core_out_latched: cocotb.handle.LogicArrayObject
    core_rounds: cocotb.handle.LogicArrayObject
    curr_state: cocotb.handle.LogicArrayObject
    encrypt_mode_i: cocotb.handle.LogicObject
    finished_o: cocotb.handle.LogicObject
    input_ready_i: cocotb.handle.LogicObject
    key: cocotb.handle.LogicArrayObject
    key_i: cocotb.handle.LogicArrayObject
    mask_high: cocotb.handle.LogicArrayObject
    mask_low: cocotb.handle.LogicArrayObject
    nonce_i: cocotb.handle.LogicArrayObject
    pad_high: cocotb.handle.LogicArrayObject
    pad_low: cocotb.handle.LogicArrayObject
    plaintext_word_left_i: cocotb.handle.LogicObject
    reset_i: cocotb.handle.LogicObject
    start_core: cocotb.handle.LogicObject
    start_core_o: cocotb.handle.LogicObject
    start_i: cocotb.handle.LogicObject
    start_prev: cocotb.handle.LogicObject
    tag_o: cocotb.handle.LogicArrayObject
    text_i: cocotb.handle.LogicArrayObject
    text_len_i: cocotb.handle.LogicArrayObject
    text_o: cocotb.handle.LogicArrayObject
    text_ready_o: cocotb.handle.LogicObject
    word_processed_o: cocotb.handle.LogicObject

    @overload
    def __getitem__(self, name: Literal['clk_i']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['reset_i']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['start_i']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['associated_data_word_left_i']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['plaintext_word_left_i']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['encrypt_mode_i']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['input_ready_i']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['start_core_o']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['finished_o']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['text_ready_o']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['word_processed_o']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['key_i']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['nonce_i']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['assoc_data_i']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['text_i']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['text_o']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['tag_o']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['text_len_i']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['start_core']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['core_finished']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['core_finished_latched']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['key']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['core_in']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['core_out']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['core_out_latched']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['core_rounds']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['curr_state']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['mask_low']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['mask_high']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['pad_low']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['pad_high']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['start_prev']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['ascon_core_inst']) -> AsconCoreInst: ...

    @overload
    def __getitem__(self, name: str) -> cocotb.handle.SimHandleBase: ...


class AsconCoreInst(cocotb.handle.HierarchyObject):
    ascon_linear_layer_inst: AsconLinearLayerInst
    ascon_sbox_inst: AsconSboxInst
    clk_i: cocotb.handle.LogicObject
    constant_addition: cocotb.handle.LogicArrayObject
    curr_state: cocotb.handle.LogicArrayObject
    finished_o: cocotb.handle.LogicObject
    internal_state: cocotb.handle.LogicArrayObject
    linear_diffusion: cocotb.handle.LogicArrayObject
    nonlinear_substition: cocotb.handle.LogicArrayObject
    reset_i: cocotb.handle.LogicObject
    round_counter: cocotb.handle.LogicArrayObject
    rounds_i: cocotb.handle.LogicArrayObject
    rounds_to_perform: cocotb.handle.LogicArrayObject
    start_i: cocotb.handle.LogicObject
    state_i: cocotb.handle.LogicArrayObject
    state_o: cocotb.handle.LogicArrayObject

    @overload
    def __getitem__(self, name: Literal['clk_i']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['reset_i']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['start_i']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['finished_o']) -> cocotb.handle.LogicObject: ...

    @overload
    def __getitem__(self, name: Literal['state_i']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['rounds_i']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['state_o']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['curr_state']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['internal_state']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['round_counter']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['rounds_to_perform']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['constant_addition']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['nonlinear_substition']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['linear_diffusion']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['ascon_sbox_inst']) -> AsconSboxInst: ...

    @overload
    def __getitem__(self, name: Literal['ascon_linear_layer_inst']) -> AsconLinearLayerInst: ...

    @overload
    def __getitem__(self, name: str) -> cocotb.handle.SimHandleBase: ...


class AsconLinearLayerInst(cocotb.handle.HierarchyObject):
    gen_slice(0): GenSlice(0)
    gen_slice(1): GenSlice(1)
    gen_slice(2): GenSlice(2)
    gen_slice(3): GenSlice(3)
    gen_slice(4): GenSlice(4)
    state_i: cocotb.handle.LogicArrayObject
    state_o: cocotb.handle.LogicArrayObject

    @overload
    def __getitem__(self, name: Literal['state_i']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['state_o']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['gen_slice(0)']) -> GenSlice(0): ...

    @overload
    def __getitem__(self, name: Literal['gen_slice(1)']) -> GenSlice(1): ...

    @overload
    def __getitem__(self, name: Literal['gen_slice(2)']) -> GenSlice(2): ...

    @overload
    def __getitem__(self, name: Literal['gen_slice(3)']) -> GenSlice(3): ...

    @overload
    def __getitem__(self, name: Literal['gen_slice(4)']) -> GenSlice(4): ...

    @overload
    def __getitem__(self, name: str) -> cocotb.handle.SimHandleBase: ...


class AsconSboxInst(cocotb.handle.HierarchyObject):
    gen_slice(0): GenSlice(0)
    gen_slice(1): GenSlice(1)
    gen_slice(2): GenSlice(2)
    gen_slice(3): GenSlice(3)
    gen_slice(4): GenSlice(4)
    state_i: cocotb.handle.LogicArrayObject
    state_o: cocotb.handle.LogicArrayObject

    @overload
    def __getitem__(self, name: Literal['state_i']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['state_o']) -> cocotb.handle.LogicArrayObject: ...

    @overload
    def __getitem__(self, name: Literal['gen_slice(0)']) -> GenSlice(0): ...

    @overload
    def __getitem__(self, name: Literal['gen_slice(1)']) -> GenSlice(1): ...

    @overload
    def __getitem__(self, name: Literal['gen_slice(2)']) -> GenSlice(2): ...

    @overload
    def __getitem__(self, name: Literal['gen_slice(3)']) -> GenSlice(3): ...

    @overload
    def __getitem__(self, name: Literal['gen_slice(4)']) -> GenSlice(4): ...

    @overload
    def __getitem__(self, name: str) -> cocotb.handle.SimHandleBase: ...

